### ISSUE TITLE
关于全节点同步模式

### ISSUE THREAD

**Issue by yufan022** [uncleguanghui/eth_kafka#1]
您好，请问是要先启动全节点同步数据后，用脚本同步至kafka吧。
这里需要ETH同步哪个模式呢？要求fast light full具体哪个模式，需要使用--gcmode=archive参数么？

**Comment by uncleguanghui** [comment]
是的，一切的前提就是你的全节点已经同步到最新数据了。

不能选择 light 模式，因为 light 模式不会同步所有交易数据。建议选择 fast 模式，在前期会加速同步速度，但是到后期也是会自动切换到 full 模式。

下面是建议的同步命令：

```commandline
geth --config /opt/bsc/config.toml \
    --datadir /opt/bsc/node \
    --pprofaddr 0.0.0.0 \
    --syncmode fast \
    --metrics \
    --pprof \
    --ws \
    --wsaddr 0.0.0.0 \
    --rpc \
    --rpcaddr 0.0.0.0 \
    --rpcvhosts '*' \
    --rpcport 8545 
    --rpccorsdomain "*" \
    --rpcapi='eth,net,web3'
```

说明：
1. `--config /opt/bsc/config.toml` 指定配置文件，没有的话就删掉；
2. `--datadir /opt/bsc/node` 指定数据路径；
3. `--ws --wsaddr 0.0.0.0` 表示开启 websocket 远程连接，且不限制 IP；
4. `--rpc --rpcaddr 0.0.0.0` 表示开启 http 远程连接，且不限制 IP；

**Comment by yufan022** [comment]
了解，对这块儿接触不是很多，还有个疑问：
启动不需要添加`--gcmode=archive`参数么？归档节点和全节点具体有什么区别呢？

**Comment by uncleguanghui** [comment]
看你需求了。归档节点（`--syncmode=full --gcmode=archive` ）比我这里说的全节点（仅 `--syncmode=full`），数据量更大更完整。因为 `--gcmode=archive` 会保留智能合约中的所有值状态以及帐户余额的完整历史记录，这些数据我几乎用不到，所以我没有添加这个参数。
